services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_WALLETCONNECT_PROJECT_ID: ${WALLETCONNECT_PROJECT_ID}
        VITE_PREDICTION_MARKET_CONTRACT_MAINNET: ${PREDICTION_MARKET_CONTRACT_MAINNET}
    # NOTE: Do NOT put secret values here in source control. Use Coolify's
    # UI to set Secrets / Environment Variables for the app instead.
    environment:
      NODE_ENV: production
      PORT: 5000
      # FRONTEND_URL is used by the server CORS checks. Set to your deployed domain.
      FRONTEND_URL: ${SERVICE_URL_APP}
      # Pass Vite env vars to runtime (though they're already baked into the build)
      VITE_WALLETCONNECT_PROJECT_ID: ${WALLETCONNECT_PROJECT_ID}
      VITE_PREDICTION_MARKET_CONTRACT_MAINNET: ${PREDICTION_MARKET_CONTRACT_MAINNET}
      # Below are additional environment variables the app reads. Provide them
      # in Coolify as secrets (do not commit actual values):
      # DEPLOYER_PRIVATE_KEY: "<private key>"             # only if you run hardhat scripts in the same environment
      # BSCSCAN_API_KEY: "<bscscan api key>"
      # VITE_PREDICTION_MARKET_CONTRACT_TESTNET: "0x..."
      # VITE_PREDICTION_MARKET_CONTRACT_MAINNET: "0x..."
      # BSC_MAINNET_RPC_URL: "https://..."
      # BSC_TESTNET_RPC_URL: "https://..."
      # DATABASE_URL: "postgres://..."                    # if using a DB (drizzle)
      # THEODDSAPI_KEY: "<odds api key>"
      # TWITTER_API_KEY: "..."
      # TWITTER_API_SECRET: "..."
      # TWITTER_ACCESS_TOKEN: "..."
      # TWITTER_ACCESS_SECRET: "..."
      # Alternate names used in code (server checks both):
      # X_API_KEY, X_API_SECRET, X_ACCESS_TOKEN, X_ACCESS_SECRET
    restart: unless-stopped
#    ports:
#      - "3000:5000"
# For Coolify you can provide environment variables in the app settings
# If your app uses a DB, add another service or use an external DB
